### ISSUE TITLE
ethernet not work

### ISSUE THREAD

**Issue by punjasin** [omegajcd/Hackintosh-OpenCore-Alder-Lake-B660M-AORUS-PRO-DDR4-RX6600M#1]
https://github.com/taruyato/b660m-aorus-pro-ddr4-hackintosh

you can use kext from this to make it work i think

**Comment by omegajcd** [comment]
Thanks my friend, I'll take this kext and do the tests. 
👍🏻✌🏻🇧🇷

**Comment by omegajcd** [comment]
Thank you friend!
kext worked.
